namespace AbpUiCli.Transformer;

public sealed class LayoutTransformer
{
    private const string AppShellContent = """
        /**
         * AppShell is the stable entry. ActiveShell is generated by the transformer.
         * To switch layouts, re-run: abp-factory transform --layout=...
         */
        export { default } from "./ActiveShell";
        """;

    public void Apply(string projectRoot, string layout)
    {
        var layoutMapPath = Path.Combine(projectRoot, "template.meta", "layout.map.json");
        if (!File.Exists(layoutMapPath))
            throw new FileNotFoundException($"Layout map not found: {layoutMapPath}. Run from a project created with abp-factory init.");

        var layoutMapJson = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(
            File.ReadAllText(layoutMapPath));
        if (layoutMapJson == null || !layoutMapJson.TryGetValue(layout, out var shellRelativePath))
        {
            var supported = layoutMapJson != null ? string.Join(", ", layoutMapJson.Keys) : "none";
            throw new ArgumentException($"Unknown layout: {layout}. Supported: {supported}");
        }

        var shellSrcPath = Path.Combine(projectRoot, shellRelativePath);
        if (!File.Exists(shellSrcPath))
            throw new FileNotFoundException($"Layout shell file not found: {shellSrcPath}");

        var appShellDir = Path.Combine(projectRoot, "src", "app-shell");
        var activeShellPath = Path.Combine(appShellDir, "ActiveShell.tsx");
        var appShellPath = Path.Combine(appShellDir, "AppShell.tsx");

        Directory.CreateDirectory(appShellDir);

        var shellContent = File.ReadAllText(shellSrcPath);
        File.WriteAllText(activeShellPath, shellContent);

        File.WriteAllText(appShellPath, AppShellContent);
    }
}
