/**
 * ActiveShell is generated by abp-ui transform. Default: sidebar layout.
 * To switch layouts, run: abp-ui transform --layout=topnav
 */
export { default } from "./layouts/sidebar/SidebarShell";
